### ISSUE TITLE
Invalid generated enums

### ISSUE THREAD

**Issue by OmiCron07** [jackyyang09/Simple-Unity-Audio-Manager#1]
My assets :
![image](https://user-images.githubusercontent.com/31325575/91743805-63c19f00-eb86-11ea-90d9-411484301695.png)

The generated enums :
````csharp
namespace JSAM {
    public enum Sounds {
        Bullet-01,
        Bullet-02
    }
    public enum Music {
    }
}
````

The name of each enum member have to be a valid name.

**Comment by jackyyang09** [comment]
The `-` character has been added to the string filter when generating enum names, for the time being, refrain from naming your AudioFile assets with a dash until the next bug-fix release
