### ISSUE TITLE
Ability to PlaySound using scriptable object argument.

### ISSUE THREAD

**Issue by killereks** [jackyyang09/Simple-Unity-Audio-Manager#14]
I would like to suggest support for using scriptable object (Audio File Object) to play the audio, with a lot of sounds in the project enums can become very difficult to work with, and when recompiling if they are re-ordered the sounds played will be wrong. I believe scriptable objects would make it safer to manage a lot of sounds.

Currently you can only do
`AudioManager.PlaySound(Sounds.sound);`
But having other ways to play sound would really help user decide what's best for the project.
`AudioManager.PlaySound(AudioFileObject soundObj);`

**Comment by jackyyang09** [comment]
Thanks for the suggestion, passing `AudioFileObjects` into AudioManager's various "Play" methods is now supported for JSAM 3.0! If you haven't already, you're free to try this feature out ahead of the full release by doing a fresh clone of the repository to your project!

Sorry for the late reply

**Comment by killereks** [comment]
Awesome! I wasn't able to find version 3.0 though. The newest I see in the releases is "v2.1.6".

**Comment by jackyyang09** [comment]
Version 3.0 is currently work-in-progress, so I won't be making a stable release until it's complete (although I might make an early beta unstable release version). Until then, if you'd like to try it, you can clone the repo directly, all the latest features will be there to try out, but I can't guarantee compatibility with your existing projects
