### ISSUE TITLE
[Feature Request] pre-create JSAMMusicFileObjects

### ISSUE THREAD

**Issue by SLiGerr** [jackyyang09/Simple-Unity-Audio-Manager#17]
Please add a function to create JSAMMusicFileObjects from a list of AudioClips (ideally from a selection in the project hierarchy), this would speed up project setup when using JSAM, especially with large amounts of music and sounds

**Comment by jackyyang09** [comment]
This request has since been addressed with the addition of the Audio File Wizard [introduced in Version 3.0](https://github.com/jackyyang09/Simple-Unity-Audio-Manager/releases/tag/v3.0.0-alpha) 

Sorry for not responding sooner
