### ISSUE TITLE
How can I adjust the volume specifically for certain types of sounds, such as voices, independently?

### ISSUE THREAD

**Issue by fegabe** [jackyyang09/Simple-Unity-Audio-Manager#19]
I have to have a independent volume slider for voice sounds since there will be voiceover sounds in my game and I want to allow to customize the volume apart from music and sounds volume

I saw that there is some code related to voices. There are even a specific AudioMixerGroup named Voices and a "VoiceVolume" parameter. I tried to use it but there are some issues. This is what I'm trying:

* I create a new sound and added to the `Sound Library` tab, e.g. for example PoemVoiceOver. 
* I set the MixerGroupOverride for that sound to use the already existing`Voices` mixer group.
* The programatically I modify the `VoiceVolume` of the voices mixer to set a specific volume for this set of voice sounds

This works until I change the global volume of the `Sounds` using `AudioManager.SetSoundVolume(newValue)`. Because this volume internally calls to a method called `OnUpdateVolume` and changes the volume of every sound `AudioSource`, including the voice sounds that I want to behave with a separated volume value.

Am I approaching incorrectly? Are the voice sounds expected to be controlled their volume in a different way?

I hope I explained it well. And thank you very much for creating this great library

**Comment by jackyyang09** [comment]
Sorry for the late response!

As you noticed, the Audio Mixer Groups don't have total control over the volume of the sound they play, in actuality, they are remnants of my old implementation of volume and they'll be removed in a later update. I do have plans to add a separate Voice volume control system, but currently, it's entirely unimplemented.

I'll be prioritizing the implementation of this feature so hopefully, you'll be able to see it in an update in the next week or so.

**Comment by fegabe** [comment]
That's great to heat. Thank you very much for answering and working on that feature. I love this library since it's very to use but really powerful. Thanks!

**Comment by jackyyang09** [comment]
Hello again fegabe,

In case you still need it, [I've just pushed out an update that adds Voice volume support!](https://github.com/jackyyang09/Simple-Unity-Audio-Manager/releases/tag/v3.0.0-preview.3)

If you happen to encounter any bugs let me know on this thread or in a new one.

_Hopefully it was worth the wait_

**Comment by fegabe** [comment]
I've just upgraded it and after a few changes it worked perfectly. Thank you very much! 🎶
