### ISSUE TITLE
AudioTriggerFeedback does not use the 'triggerWith' property

### ISSUE THREAD

**Issue by OmiCron07** [jackyyang09/Simple-Unity-Audio-Manager#2]
The property `LayerMask triggersWith` in `AudioTriggerFeedback` class is not used at all.

**Comment by jackyyang09** [comment]
It seems I forgot about the layer comparison while refactoring the class, a fix will be out by the end of the week. For the time being, do refer to the contents of the `AudioCollisionFeedback` class to replicate the same functionality
