### ISSUE TITLE
Some issues detected in new 3.0 Alpha Preview 3

### ISSUE THREAD

**Issue by fegabe** [jackyyang09/Simple-Unity-Audio-Manager#20]
Hello,

Because of this #19 issue I've recently updated to latest preview and after some testing I wanted to report some issues I've found to help improving it. First of all, the sound voice setting has been really helpful and it's working great. It's just a few minor things I've found:

- There is a warning that says: "A meta data file (.meta) exists but its folder 'Assets/ThirdParty/JSAM/Editor/Samples~' can't be found, and has been created". 
   - This is because the special behaviour of having a folder ending in ~, just removing the meta file seems to fix it.

- When having the editor flag to play quicker (see https://cln.sh/3Vjvtpmd) changing the volume generate errors (see https://cln.sh/LSWtX5dH)
   - It's very useful having this flag on to iterate quicker during development although it may have side effects like this with some code. I didn't go why is this being caused but usually could be fixed resetting properly the references when detecting the GameObjects are being destroyed

- Error when generating a build, see https://cln.sh/sd67BCJ8
   - There is some editor-only code at `JamSettings.cs` file. Wrapping the affected lines within the UNITY_EDITOR macro fixes it (https://cln.sh/JhQmyJg6) but I'm not sure if it's the best solution without knowing deeper the library code

I hope this explanation helps fixing it. For now I'm downloading the library instead of using the git syncronization to be able to have the quick fixes I've found locally so it's not stopping me. 

Thank you very much for you work.

**Comment by jackyyang09** [comment]
Hi fegabe,

Thanks for the detailed feedback! I haven't had the time to do a lot of testing, but try this fix when using the Configurable Play Mode settings.

In `AudioManager.cs` try adding the following code block anywhere.
```
[RuntimeInitializeOnLoadMethod]
static void RunOnStart()
{
    OnAudioManagerInitialized = null;
    OnSoundPlayed = null;
    OnVoicePlayed = null;
    OnMusicPlayed = null;
    OnMasterVolumeChanged = null;
    OnMusicVolumeChanged = null;
    OnSoundVolumeChanged = null;
    OnVoiceVolumeChanged = null;
}
```

As for the error when building, your fix is good and won't break anything. I just forgot to wrap up the editor code 😵

**Comment by fegabe** [comment]
I've upgraded to the latest version in the repo and it's working perfectly, thank you very much!
