### ISSUE TITLE
Preset file in immutable folder

### ISSUE THREAD

**Issue by MeisterDerMagie** [jackyyang09/Simple-Unity-Audio-Manager#24]
I tried to use the "Create Preset from this Audio File" button. Apparently the preset will be generated inside the package folder which isn't allowed by Unity. The following error pops up.

```
Asset Packages/com.brogrammist.jsam/Runtime/Presets/MusicAssetPreset.preset has no meta file, but it's in an immutable folder. The asset will be ignored.
UnityEditor.AssetDatabase:Refresh ()
Eflatun.SceneReference.Editor.SceneDataMapsGenerator:Run () (at ./Library/PackageCache/com.eflatun.scenereference@c94f1c9902/Editor/SceneDataMapsGenerator.cs:47)
Eflatun.SceneReference.Editor.MapGeneratorTriggers.SceneAssetPostprocessor:OnPostprocessAllAssets (string[],string[],string[],string[]) (at ./Library/PackageCache/com.eflatun.scenereference@c94f1c9902/Editor/MapGeneratorTriggers/SceneAssetPostprocessor.cs:21)
UnityEditor.EditorApplication:Internal_CallGlobalEventHandler ()
```

**Comment by MeisterDerMagie** [comment]
I see just now that this error is thrown by a different package we use. Still, the presets should not be stored inside the package folder because they will not be pushed to git.

**Comment by jackyyang09** [comment]
Thanks for reporting the issue! The default save path shall be changed in a future release, for the time being, you can work around this by changing your project's preset save path. 

You can do this by navigating to `Project Settings -> Audio JSAM -> Editor -> Presets Path` and setting the path to somewhere in your `Assets/` folder.

**Comment by jackyyang09** [comment]
Issue fixed in latest Release
