### ISSUE TITLE
Audio not spatialized first time

### ISSUE THREAD

**Issue by samaelxxi** [jackyyang09/Simple-Unity-Audio-Manager#25]
SetSpatializationTarget in BaseAudioChannelHelper returns on 
if (!audioFile) return;
line because audioFile setuped only in helper.Play(sound); which happens after Spatialization
probably related to the last fix:
Fixed AudioSource spatialization only happening after the sound is played

Steps to reproduce:
Make spatialized sound with distance for example 30.
Place listener and sound position somewhere at (-40, 0, 0)
Trigger sound - it's not spatialized(therefore can't be heared), AudioChannel object has (0, 0, 0) position.
Wait until sound ends and trigger again - it will be spatialized because it has audioclip now.

**Comment by jackyyang09** [comment]
This issue should now be fixed with the latest [release](https://github.com/jackyyang09/Simple-Unity-Audio-Manager/releases/tag/v3.0.0-preview.7).
