### ISSUE TITLE
[Bug] Inspector Bug on Audio Asset missing

### ISSUE THREAD

**Issue by StinkySteak** [jackyyang09/Simple-Unity-Audio-Manager#36]
![image](https://github.com/jackyyang09/Simple-Unity-Audio-Manager/assets/52377879/2580ede7-9507-4c8c-b7f7-343e3a0e853b)

The inspector will not draw if the audio file is missing. Thus we have to go to debug mode to fix it, because anything is not clickable

### Steps To Reproduce
1. Create a sound File Object
2. Attach an Audio into It
3. Delete the Audio Asset

```
NullReferenceException: Object reference not set to an instance of an object
JSAM.JSAMEditor.SoundFileObjectEditor.OnInspectorGUI () (at Library/PackageCache/com.brogrammist.jsam@89243ec951/Editor/SoundFileObjectEditor.cs:291)
UnityEditor.UIElements.InspectorElement+<>c__DisplayClass59_0.<CreateIMGUIInspectorFromEditor>b__0 () (at <cd89fd1ce037419f95985196f5aeee4d>:0)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr, Boolean&)
```

Unity Version: 2021.21f1
JSAM: 3.0.0-preview 6

**Comment by jackyyang09** [comment]
Sorry for the delay, this issue has now been fixed as of [Version 3.0.1](https://github.com/jackyyang09/Simple-Unity-Audio-Manager/releases/tag/v3.0.1)
