### ISSUE TITLE
UnityEngine Timeline dependency

### ISSUE THREAD

**Issue by StinkySteak** [jackyyang09/Simple-Unity-Audio-Manager#38]
I just updated my jsam to from 3.0.0-pv-6 to 3.0.1, now there is errors about `UnityEngine.Timeline` namespace.
Unity Version: 2022.3.27f1.

- I don't have timeline package installed
- Is this necessary?

**Comment by jackyyang09** [comment]
Sorry for the issue, it has been fixed in the 3.0.2 release.
