### ISSUE TITLE
FadeMusicIn always returns the mainMusic channel.

### ISSUE THREAD

**Issue by LoiNV83** [jackyyang09/Simple-Unity-Audio-Manager#45]
Hello,
I am using your JSAM library and have encountered an issue when calling:
`var channelHelper = AudioManager.FadeMusicIn(this.audioLibraryMusic, 3, false);`
I noticed that channelHelper always returns the mainMusic channel, even though the music is playing on a different channel.

May I ask if this is a bug, or is it the intended behavior of the function?
I apologize for my English.

Thank you!

**Comment by jackyyang09** [comment]
Hi LoiNV83, this is indeed a bug, it will be fixed in the next release.

For now, you can open up the class `AudioManagerInternal.cs`, look for the function `FadeMusicInInternal` and replace 
`return mainMusic;`
with
`return helper`

**Comment by LoiNV83** [comment]
Thank you for reviewing! I will update the new version when available.
