### ISSUE TITLE
Is there any way to schedule?

### ISSUE THREAD

**Issue by dsinkerii** [jackyyang09/Simple-Unity-Audio-Manager#46]
Hello there! I really like this repo as its very easy to use.
I'm currently making a simple music manager using JSAM to manage music with phases, however, that would require JSAM to schedule playing the audiosource at a specific timestamp, and i can't quite figure out how to do it.

My current setup is a basic script that references the audio library, and when the test function is called to change phases, it fades both phases to smoothly lerp, however due to the fact that it's done in FixedUpdate function, there's a slight hiccup in the time between both phases.

Here's a test snippet of how it currently works:
```c#
void UpdateTiming(){
        if(!IsPlaying) return;
        QBeats = (int)((AudioSettings.dspTime - startTime) * BPM / 60.0); // measure in quarter beats
        if(oldQ != QBeats){
            oldQ = QBeats; // snap
            if(RequestedToInterpolate && trackProfiles[0].phases[0].SnapToBeat && (QBeats % trackProfiles[0].phases[0].QuarterBeatResolution) == 0){
                print("Snap!");
                JSAM.AudioManager.FadeMainMusicOut(trackProfiles[0].phases[0].fadeOutTime);
                JSAM.AudioManager.FadeMusicIn(trackProfiles[0].phases[1].mainClip, trackProfiles[0].phases[0].fadeOutTime, true);
                RequestedToInterpolate = false;
            }
        }
    }
    void FixedUpdate()
    {
        UpdateTiming();
    }
    [ContextMenu("Play")]
    void Play(){
        startTime = AudioSettings.dspTime;
        JSAM.AudioManager.PlayMusic(trackProfiles[0].phases[0].mainClip, true);
        IsPlaying = true;
        BPM = trackProfiles[0].bpm;
        QBeats = 0;
    }

    [ContextMenu("Fade")]
    void FadePlay(){
        if(trackProfiles[0].phases[0].SnapToBeat)
            RequestedToInterpolate = true;
        else{
            JSAM.AudioManager.FadeMainMusicOut(trackProfiles[0].phases[0].fadeOutTime);
            JSAM.AudioManager.FadeMusicIn(trackProfiles[0].phases[1].mainClip, trackProfiles[0].phases[0].fadeOutTime, true);
        }
    }
    ```
    
    music file objects:
    
![image](https://github.com/user-attachments/assets/e71013b4-41c3-48c5-bc57-06a349801058)
![image](https://github.com/user-attachments/assets/8ea8e782-5e01-42a2-bb5f-b6f0234460d8)

**Comment by jackyyang09** [comment]
Hi dsinkerii,

While there isn't a built-in way to "schedule" behavior, you can try to manually readjust the playback position of your music based on your needs.

Most of AudioManager's method calls will return a SoundChannelHelper or MusicChannelHelper that exposes the AudioSource that is being used to perform playback operations on the referenced audio files.

You can then do something like the following:

```cs
var helper1 = JSAM.AudioManager.FadeMainMusicOut(trackProfiles[0].phases[0].fadeOutTime);
var helper 2 = JSAM.AudioManager.FadeMusicIn(trackProfiles[0].phases[1].mainClip, trackProfiles[0].phases[0].fadeOutTime, true);

float transitionTime = // Get the transition time in seconds

// Readjust current playback position to fade from desired point
helper1.AudioSource.time = transitionTime;
helper2.AudioSource.time = transitionTime;
```

Hope this helps

**Comment by dsinkerii** [comment]
that solved it, thanks!
