### ISSUE TITLE
Documentation does not cover how to add multiple files to a single object

### ISSUE THREAD

**Issue by willWashington** [jackyyang09/Simple-Unity-Audio-Manager#6]
Perhaps I'm missing it, but I can't find a way to get this object created. I have 88 songs as of this writing that I need to add to an object such that AudioManager can play it as Music. 

Do I have to add every single one of those songs individually via the New Music button on the Manager object, or can I somehow inject them all at once?

![image](https://user-images.githubusercontent.com/22458888/93639632-54848300-f9c7-11ea-91df-d9c54803b915.png)

**Comment by jackyyang09** [comment]
Currently on Audio File Objects support the use of _Libraries_, where a single _Audio File Object_ can support multiple AudioClips. Libraries target the use case of playing a specific sound (gun shot noise) to a random unique variant of said sound (gunshot001.wav of 10) play in it's stead every time the sound is to be played. Enabling this option can be done with the _Use Library_ checkbox.

Manually adding individual tracks is admittedly a bit tedious at the moment and a better interface will be made for that down the road. However, I'm curious as to why you want 88 tracks to be placed in a single Audio File, do let me know what you're trying to do. If your use case requests a specific new feature, I can note it down to add in the future. 

In the short term, the alternative to adding a new music file through the Audio Manager is to navigate to the folder holding the objects in the Project window or your File Manager and duplicating/copy+pasting the .asset files. This will at least allow you to get around the pop-up dialogues.
