### ISSUE TITLE
Audio source picker gone in editor

### ISSUE THREAD

**Issue by omrirosen** [jackyyang09/Simple-Unity-Audio-Manager#7]
Hi Jacky!

Love your audio manager, thanks for sharing it for free. A short while after starting work with the manager, the music\sound files generated by the manager no longer show an audio source picker in the inspector. Not sure what causes this.

**Comment by omrirosen** [comment]
got this exception, hope it helps

NullReferenceException: Object reference not set to an instance of an object
JSAM.AudioFileMusicObjectEditor.CheckIfNameChanged () (at Assets/Plugins/Jacky's Simple Audio Manager/Editor/AudioFileMusicObjectEditor.cs:822)
JSAM.AudioFileMusicObjectEditor.OnInspectorGUI () (at Assets/Plugins/Jacky's Simple Audio Manager/Editor/AudioFileMusicObjectEditor.cs:119)
UnityEditor.UIElements.InspectorElement+<>c__DisplayClass58_0.<CreateIMGUIInspectorFromEditor>b__0 () (at <d3ff43e972b043d1b3f49905ec5da738>:0)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)

**Comment by jackyyang09** [comment]
Hey thanks for writing a report! I've just posted a new version in the Release page which should fix the bug you've happened upon

Do let me know if you encounter any more problems!
